framework:
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 3600
        save_path: '%kernel.project_dir%/var/sessions'
        metadata_update_threshold: 0 