CREATE TABLE follow (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, follower_id INTEGER NOT NULL, followed_id INTEGER NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, CONSTRAINT FK_68344470AC24F853 FOREIGN KEY (follower_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_68344470D956F010 FOREIGN KEY (followed_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_68344470AC24F853 ON follow (follower_id);
CREATE INDEX IDX_68344470D956F010 ON follow (followed_id);
CREATE UNIQUE INDEX unique_follow ON follow (follower_id, followed_id);
CREATE TABLE commentaire (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, publication_id INTEGER NOT NULL, parent_id INTEGER DEFAULT NULL, content CLOB NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, updated_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
, CONSTRAINT FK_67F068BCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_67F068BC38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_67F068BC727ACA70 FOREIGN KEY (parent_id) REFERENCES commentaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_67F068BCA76ED395 ON commentaire (user_id);
CREATE INDEX IDX_67F068BC38B217A7 ON commentaire (publication_id);
CREATE INDEX IDX_67F068BC727ACA70 ON commentaire (parent_id);
CREATE TABLE "user" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles CLOB NOT NULL --(DC2Type:json)
, password VARCHAR(255) NOT NULL, username VARCHAR(180) DEFAULT NULL);
CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email);
CREATE TABLE publication (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, texte CLOB NOT NULL, image VARCHAR(255) DEFAULT NULL, video VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, updated_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
, CONSTRAINT FK_AF3C6779A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_AF3C6779A76ED395 ON publication (user_id);
CREATE TABLE "like" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, publication_id INTEGER NOT NULL, CONSTRAINT FK_AC6340B3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_AC6340B338B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_AC6340B3A76ED395 ON "like" (user_id);
CREATE INDEX IDX_AC6340B338B217A7 ON "like" (publication_id);
CREATE UNIQUE INDEX unique_like ON "like" (user_id, publication_id);
CREATE TABLE comment_like (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, commentaire_id INTEGER NOT NULL, CONSTRAINT FK_8A55E25FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_8A55E25FBA9CD190 FOREIGN KEY (commentaire_id) REFERENCES commentaire (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_8A55E25FA76ED395 ON comment_like (user_id);
CREATE INDEX IDX_8A55E25FBA9CD190 ON comment_like (commentaire_id);
CREATE UNIQUE INDEX unique_comment_like ON comment_like (user_id, commentaire_id);
CREATE TABLE repost (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, publication_id INTEGER NOT NULL, user_id INTEGER NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, updated_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
, CONSTRAINT FK_DD3446C538B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_DD3446C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
CREATE INDEX IDX_DD3446C538B217A7 ON repost (publication_id);
CREATE INDEX IDX_DD3446C5A76ED395 ON repost (user_id);
CREATE UNIQUE INDEX UNIQ_REPOST_USER_PUBLICATION ON repost (user_id, publication_id);
CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, available_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
, delivered_at DATETIME DEFAULT NULL --(DC2Type:datetime_immutable)
);
CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name);
CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at);
CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at);
